> # **Métodos Computacionales I - Taller #3**

**Hecho por:** Claudia Alejandra Cuellar Nieto & Thomas Andrade Hernández


In [2]:
# Zona de librerías:
import urllib.request
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim
from mpl_toolkits.mplot3d import axes3d
from matplotlib import rc
import sympy as sym
import pandas as pd
from tqdm import tqdm
from time import sleep
import os.path as path
import os
import wget

> # **5. ÁLGEBRA LINEAL**

**$3)\verb| (Python)|$** Implemente un algoritmo que realice la multiplicación de dos matrices. Use el algoritmo para calcular:

$$
\mathbb{AB}

=

\begin{pmatrix}
    1 & 0 & 0\\
    5 & 1 & 0\\
    -2 & 3 & 1
\end{pmatrix}

\cdot 

\begin{pmatrix}
    4 & -2 & 1\\
    0 & 3 & 7\\
    0 & 0 & 2
\end{pmatrix}$$

In [3]:
def GetMultiplication(A,B):
    matrix_column = []
    for i in range(len(B)):
        column = []
        for j in range(len(B)): 
            column.append(B[j][i])
        matrix_column.append(column)
    

    multiplication_matrix =[]
    for k in A:
        new_matrix = []
        for w in matrix_column:
            new_matrix.append(np.dot(k,w))
        multiplication_matrix.append(new_matrix)
        
    return np.array(multiplication_matrix)

In [4]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])

print("El resultado de la multiplicación entre las matrices dadas es:\n {}".format(GetMultiplication(A,B)))

El resultado de la multiplicación entre las matrices dadas es:
 [[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]


**$4)\verb| (Theoretical)|$** Muestre con detalle que la sustitución hacia adelante se expresa como:

$$x_{i} = b_{i} - \sum_{j = 0}^{i - 1} A_{ij} \cdot x_{j}$$

**Respuesta:**

Este método de sustitución hacia delante se usa especialmente para solucionar sistemas de la forma $Lx = b$ donde L es la matriz triangular inferior que aparece en la factorización de una matriz A. Así, sea el sistema de solución de matrices dado por,

$$ \begin{bmatrix}
l_{11} & 0 & 0  \\
l_{21} & l_{22} & 0  \\
l_{31} & l_{32} & l_{33}  \\

\end{bmatrix} 
\begin{bmatrix}
x_1  \\
x_2  \\
x_3 
\end{bmatrix} 
= 
\begin{bmatrix}
b_1  \\
b_2  \\
b_3 
\end{bmatrix} 
$$

La solución para la primera variable sería de la forma,

$$ L_{11} x_1 = b_1 \rightarrow x_1 = \frac{b_1}{L_{11}} $$

La solución para la segunda variable sería de la forma,

$$ L_{21} x_1 + L_{22} x_2 = b_2 $$

Sustituyendo $x_1$ y despejando la para $x_2$ obtenemos que,

$$ x_2 = \frac{b_2 - L_{21} (b_1/L_{11})}{L_{22}} $$

Para la solución de la tercera variable obtenemos que,
$$ L_{33}  x_3 + L_{31} x_1 + L_{32}  x_2 = b_3 $$

Como podemos observar la i-ésima solución dependerá de las soluciones anteriores por lo que la sumatoria se puede escribir de la forma, 

$$ b_i =  \sum_{j=1}^{i} A_{ij}  x_j $$

Sin embargo, si queremos despejar la variable i-ésima, debemos de cambiar los índices de la sumatoria y extraer el término de que deseamos,

$$ b_i =  L_{ii} x_i + \sum_{j=0}^{i-1} A_{ij}  x_j \rightarrow L_{ii}x_i = b_i - \sum_{j=0}^{i-1} A_{ij}  x_j$$

En este caso, la matriz factorizada L tiene la particularidad que su diagonal está compuesta solo por números uno. Por lo que nuestra ecuacion queda reducida a,

$$ x_i = b_i -  \sum_{j=0}^{i-1} A_{ij}  x_j $$

Y así queda mostrada la ecuación del enunciado para el método de sustitución hacia atrás.

- **$5) \verb| (Theoretical)|$** Muestre con detaller que la sustitución hacia atrás se expresa como:

$$x_{i} = \frac{b_{i} - \sum_{j = i + 1}^{n} A_{ij} \cdot x_{j}}{A_{ii}}$$

donde $i = n, n - 1, ..., 0$. Note que la diagonal de la matriz triangular puede tener cualquier valor.


- **$6) \verb| Successive over-relaxation (SOR)|$**. El método de sobre relajación sucesiva se basa en los métodos de Jacobi y Gauss-Seidel, pero incluye un parámetro de escala que reduce el error de aproximación en el paso $(k)$. La formula iterativa está dada por:

$$x_{i}^{(k)} = (1 - \omega) \cdot x_{i}^{(k - 1)} + \frac{\omega}{a_{ii}} \cdot \left[ b_{i} - \sum_{j = 1}^{i - 1} a_{ij}x_{j}^{(k)} -  \sum_{j = 1}^{i - 1} a_{ij}x_{j}^{(k - 1)}\right]$$

donde $i$ se refiere a la componente del vector, el índice $k$ al paso de la iteración y $0 < \omega < 2$ es parámetro de relajación. Implemente este método para solucionar el sistema de ecuaciones de clase $(5.4)$ y encuentre el parámetro de relajación que minimiza el número de iteraciones para resolverlo. Cuando $1 < \omega < 2$ el método se denomina SOR.


**$7)\verb| (Python)|$** Implemente la descomposición $LU$ para factorizar la siguiente matriz $\mathbb{A} = LU$:

$$
\mathbb{A}

=

\begin{pmatrix}
    4 & -2 & 1\\
    20 & -7 & 12\\
    -8 & 13 & 17
\end{pmatrix}

=

\begin{pmatrix}
    1 & 0 & 0\\
    5 & 1 & 0\\
    -2 & 3 & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
    4 & -2 & 1\\
    0 & 3 & 7\\
    0 & 0 & -2
\end{pmatrix}
$$

In [5]:
def FactorizationLU(m):
    A = np.array(m)
    n = A.shape[0]
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    
    for j in range(n):
        L[j][j] = 1.0
        
        for i in range(j+1,n):
            L[i][j] = A[i][j] / A[j][j]
            
            for k in range(j+1,n):
                A[i][k] = A[i][k] - L[i][j]*A[j][k]
                
        for k in range(j,n):
            U[j][k] = A[j][k]
    
    return L,U

In [6]:
M = np.array([[4,-2,1],[20,-7,12],[-8,13,17]])
L,U = FactorizationLU(M)

print("Dada la matriz A su respectiva factorización es: \n L: \n {} \n U: \n {}".format(L,U))

Dada la matriz A su respectiva factorización es: 
 L: 
 [[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]] 
 U: 
 [[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


**$9)\verb| Método de Jacobi: Diagonalización de matrices simétricas.|$** Cuando la matriz es simétrica $a_{ij}= a_{ji}$, es posible encontrar todos los valores y vectores propios mediante la transformación de la matriz $\mathbb{A}$ usando matrices de rotación. En particular, una rotación alrededor del eje $z$ está dada por:

$$R(\theta) = 
\begin{pmatrix}
\cos\theta & -\sin\theta & 0\\
\sin\theta & \cos\theta & 0\\
0 & 0 & 1
\end{pmatrix}$$

donde $i, j$ es la posición del elemento más grande fuera de la diagonal. Investigue en la literatura el algoritmo de Jacobi para diagonalizar matrices simétricas.

$(a)$ Implemente el método de Jacobi para encontrar los valores propios de:

$$ \mathbb{A} = 
\begin{pmatrix}
4 & 1 & 1\\
1 & 3 & 2\\
1 & 2 & 5
\end{pmatrix}
$$


In [7]:
def GetJacobiEig(A, it=1000):
    n = A.shape[0]
    #Matriz para los valores propios.
    D = A.copy()
    #Matriz para los vectores propios.
    B = -np.eye(n)
     
    #Encontrar los índices del máximo elemento no diagonal. 
    for k in range(it):
        max_index = (0, 0)
        max_value = 0
        for i in range(n):
            for j in range(i+1, n):
                value = np.abs(D[i][j])
                if value > max_value:
                    max_value = value
                    max_index = (i,j)
        
        #Indice de la fila.          
        i = max_index[0]
        #Indice de la columna.
        j = max_index[1]

        #Se calcula el ángulo de rotación teniendo en cuenta los signos del cuadrante.
        if D[i][i] == D[j][j]:
            theta = np.pi / 4
        else:
            t = (2 * D[i][j]) / (D[j][j] - D[i][i]) 
            if t >= 0:
                theta = 0.5 * np.tan(t)
            else:
                theta = 0.5 * np.tan(t) + np.pi
        
        #Se asignan los valores para la matriz de rotación.
        R = np.eye(n)
        R[i][i] = np.cos(theta)
        R[j][j] = np.cos(theta)
        R[i][j] = np.sin(theta)
        R[j][i] = -np.sin(theta)

        #Se actualizan las matrices D y B
        #Para los valores propios será el producto punto entre la transpuesta de R, y el producto punto de D y R.
        D = np.dot(R.T, np.dot(D, R))
        #Para los vectores propios será el producto punto de la matriz B existente y R.
        B = np.dot(B, R)


    #Los valores propios serán la diagonal de la matriz D.
    eigen_values = np.diag(D)
    #Los vectores propios serán la matriz B.
    eigen_vectors = B

    return eigen_values, eigen_vectors

In [8]:
C = np.array([[4,1,1],[1,3,2],[1,2,5]])
values,vectors = GetJacobiEig(C)

print("Mediante el método de Jacobi los valores propios de la matriz son {} \n y sus repectivos vectores propios:\n {}".format(values,vectors))

Mediante el método de Jacobi los valores propios de la matriz son [6.89510652 3.39729507 1.70759841] 
 y sus repectivos vectores propios:
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


$(b)$ Compare con el resultado que se obtiene de Numpy: $\verb|np.align.eig(A)|$.

In [9]:
values,vectors = np.linalg.eig(C)
print("Los valores propios de la matriz son {} \n y sus repectivos vectores propios:\n {}".format(values,vectors))

Los valores propios de la matriz son [6.89510652 3.39729507 1.70759841] 
 y sus repectivos vectores propios:
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


Como se puede observar, se llegan a los mismos valores y vectores propios por el método de Jacobi.

- **$10)\verb| Quantum system - ground state.|$** Un sistema cuántico de tres niveles está descrito por el siguiente Hamiltoniano:

$$\hat{H} = 
\begin{pmatrix}
1 & 2 & -1\\
1 & 0 & 1\\
4 & -4 & 5
\end{pmatrix}$$

Implemente el algoritmo de la potencia inversa para encontrar el valor del estado base $E_0$ y su vector propio $\lvert \varphi_{0} \rangle$. **Ans.** $E_{0} = 1$ y $\lvert \varphi_{0} \rangle = [0.40824829, −0.40824829, −0.81649658]$.

- **$12)\verb| Jacobiano de cuarto orden.|$** Usando el operador derivada central de orden $\mathfrak{O}(h^4)$ es posible mejorar la estimación del Jacobiano para funciones vectoriales.

$(a)$ Escriba una función que estime el Jacobiano con el operador derivada de orden $\mathfrak{O}(h^4)$.

$(b)$ Estime el Jacobiano de la siguiente función en el punto $x = (0.5, 0.5, 0.5)$ con $h = 0.01$:

$$6x_{1} - 2\cos(x_{2}x_{3}) - 1 = 0$$
$$9x_{2} + \sqrt{x_{1}^2 + \sin(x_{3}) +1.06} + 0.9 = 0$$
$$60x_{3} + 3e^{-x_{1}x_{2}} + 10\pi - 3 = 0$$

$(c)$ Estime el Jacobiano usando la aproximación de orden $\mathfrak{O}(h^2)$ con $h = 0.01$. Para qué valor de $h$, el operador de segundo orden igualará en precisión al operador de cuarto orden; verifique su intuición en el código.

- **$13)\verb| (Group theory, Sympy)|$**  El grupo de rotación $SO3$ (special orthogonal dim 3) describe las rotaciones en el espacio. Este grupo tiene el siguiente conjunto de generadores:

$$J_{x} = 
\begin{pmatrix}
0 & 0 & 0\\
0 & 0 & -1\\
0 & 1 & 0
\end{pmatrix},

J_{y} = 
\begin{pmatrix}
0 & 0 & 1\\
0 & 0 & 0\\
-1 & 0 & 0
\end{pmatrix},

J_{z} = 
\begin{pmatrix}
0 & -1 & 0\\
1 & 0 & 0\\
0 & 0 & 0
\end{pmatrix}.
$$

Verifique que el álgebra de Lie del grupo está dada por:

$$[J_{i}, J_{j}] = \epsilon_{ijk}J_{k}, \quad i, j = 1, 2, 3$$

donde $[A, B] = AB - BA$ es el conmutador y el símbolo Levi-Civita está definido por:

$$\epsilon_{ijk} = \left\{
        \begin{array}{cc}
        +1 \quad & \text{si} \quad & (i, j, k) = (1, 2, 3), (2, 3, 1), (3, 1, 2) \quad \text{Permutación par}\\
        \\
        -1 \quad & \text{si} \quad & (i, j, k) = (3, 2, 1), (1, 3, 2), (2, 1, 3) \quad \text{Permutación impar}\\
        \\
        0 \quad & \text{de otro modo} \quad & i = j \text{ o } j = k \text{ o } k = i
        \end{array}
        \right.
        $$

**$14)\verb| (Group theory, Sympy)|$**  El grupo de rotación $SU2$ (special unitary dim 2) describe el operador del espín para una partícula fundamental con $s = 1/2$. Este grupo tiene el siguiente conjunto de generadores:

$$\sigma_{x} = 
\begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix},

\sigma_{y} = 
\begin{pmatrix}
0 & -i\\
i & 0
\end{pmatrix}, 

\sigma_{z} = 
\begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix}$$

Verifique que el álgebra de Lie del grupo está dada por:

$$[\sigma_{i}, \sigma_{j}] = 2i\epsilon_{ijk}\sigma_{k}, \quad i, j = 1, 2, 3.$$

donde $[A, B] = AB - BA$ es el conmutador.

**$15)\verb| (Particle Physics, Sympy)|$**  Las matrices de Dirac $\{\gamma^{0}, \gamma^{1}, \gamma^{2}, \gamma^{3}\}$ Son una representación del álgebra de Clifford $Cl_{1, 3}(\mathbb{R})$, que transforman correctamente el espacio de espinores de la teoría cuántica de campos:

$$\gamma^0 = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 0 & 0 & -1
\end{pmatrix}, \quad 

\gamma^1 = 
\begin{pmatrix}
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0\\
0 & -1 & 0 & 0\\
-1 & 0 & 0 & 0
\end{pmatrix}$$

$$\gamma^2 = 
\begin{pmatrix}
0 & 0 & 0 & -i\\
0 & 0 & i & 0\\
0 & i & 0 & 0\\
-i & 0 & 0 & 0
\end{pmatrix}, \quad 

\gamma^3 = 
\begin{pmatrix}
0 & 0 & 1 & 0\\
0 & 0 & 0 & -1\\
-1 & 0 & 0 & 0\\
0 & 1 & 0 & 0
\end{pmatrix}$$

Verifique que el álgebra de Clifford está dada por una relación de anticonmutación.

$$\{\gamma^{\mu}, \gamma^{\delta}\} = \gamma^{\mu}\gamma^{\delta} + \gamma^{\delta}\gamma^{\mu} = 2\eta^{\mu\delta} \mathbb{I}_{4 \times 4}$$

donde $\eta^{\mu\delta} = diag(+1, -1, -1, -1)$ es la métrica del espacio de la relatividad especial.

**Respuesta:**

Dadas las matrices de Dirac se puede comprobar la propiedad anticonmutación la cual, asegura que se genere una representación matricial en el álgebra de Clifford dada por la siguiente relación:

$$ \gamma^u \gamma^v + \gamma^v \gamma^u = 2\mu^{uv} I_{4x4} \rightarrow \mu^{uv} = diag(1,-1,-1,-1)$$

Para comprobar la anterior relación, tomaremos dos casos específicos, cuando $u\neq v$ y $u=v$ . Para el primer caso, podemos observar que sin importar el orden de los índices, el resultado obtenido es la matriz cero.

In [11]:
i = sym.Symbol('i')
gamma_zero = np.array([[1,0,0,0],[0,1,0,0],[0,0,-1,0],[0,0,0,-1]])
gamma_one = np.array([[0,0,0,1],[0,0,1,0],[0,-1,0,0],[-1,0,0,0]])
gamma_two = np.array([[0,0,0,-i],[0,0,i,0],[0,i,0,0],[-i,0,0,0]])
gamma_three = np.array([[0,0,1,0],[0,0,0,-1],[-1,0,0,0],[0,1,0,0]])

def GetRelation(a,b):
    z = GetMultiplication(a,b) + GetMultiplication(b,a)
    return sym.Matrix(z)

In [12]:
one = GetRelation(gamma_zero,gamma_one)
print("Para gamma^0 y gamma^1 obtenemos:")
one

Para gamma^0 y gamma^1 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [13]:
two = GetRelation(gamma_zero,gamma_two)
print("Para gamma^0 y gamma^2 obtenemos:")
two

Para gamma^0 y gamma^2 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [14]:
three = GetRelation(gamma_zero,gamma_three)
print("Para gamma^0 y gamma^3 obtenemos:")
three

Para gamma^0 y gamma^3 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [15]:
four = GetRelation(gamma_one,gamma_two)
print("Para gamma^1 y gamma^2 obtenemos:")
four

Para gamma^1 y gamma^2 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [16]:
five = GetRelation(gamma_one,gamma_three)
print("Para gamma^1 y gamma^3 obtenemos:")
five

Para gamma^1 y gamma^3 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

In [17]:
six = GetRelation(gamma_two,gamma_three)
print("Para gamma^2 y gamma^3 obtenemos:")
six

Para gamma^2 y gamma^3 obtenemos:


Matrix([
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

Con respecto al segundo caso, se puede observar que para la matriz $\gamma^0$ la relación da como resultado $2\mathbb{I}_{4x4}$. En cambio, para el resto de índices el resultado es $-2\mathbb{I}_{4x4}$ donde $\mathbb{I}$ es la matriz identidad.

In [18]:
one = GetRelation(gamma_zero,gamma_zero)
print("Para gamma^0 obtenemos:")
one

Para gamma^0 obtenemos:


Matrix([
[2, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 2, 0],
[0, 0, 0, 2]])

In [19]:
two = GetRelation(gamma_one,gamma_one)
print("Para gamma^1 obtenemos:")
two

Para gamma^1 obtenemos:


Matrix([
[-2,  0,  0,  0],
[ 0, -2,  0,  0],
[ 0,  0, -2,  0],
[ 0,  0,  0, -2]])

In [20]:
three = GetRelation(gamma_two,gamma_two)
print("Para gamma^2 obtenemos:")
three

Para gamma^2 obtenemos:


Matrix([
[2*i**2,      0,      0,      0],
[     0, 2*i**2,      0,      0],
[     0,      0, 2*i**2,      0],
[     0,      0,      0, 2*i**2]])

In [21]:
four = GetRelation(gamma_three,gamma_three)
print("Para gamma^3 obtenemos:")
four

Para gamma^3 obtenemos:


Matrix([
[-2,  0,  0,  0],
[ 0, -2,  0,  0],
[ 0,  0, -2,  0],
[ 0,  0,  0, -2]])

Dados estos resultados, se puede representar dicha relación de anticonmutación en una matriz cuyas filas y columnas estarán determinados por los índices de las matrices $u$ y $v$ respectivamente como se muestra a continuación,

$$\begin{bmatrix}
(\gamma^0,\gamma^0) & (\gamma^0,\gamma^1) & (\gamma^0,\gamma^2) & (\gamma^0,\gamma^3) \\
(\gamma^1,\gamma^0) & (\gamma^1,\gamma^1) & (\gamma^1,\gamma^2) & (\gamma^1,\gamma^3) \\
(\gamma^2,\gamma^0) & (\gamma^2,\gamma^1) & (\gamma^2,\gamma^2) & (\gamma^2,\gamma^3) \\
(\gamma^3,\gamma^0) & (\gamma^3,\gamma^1) & (\gamma^3,\gamma^2) & (\gamma^3,\gamma^3) 
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & -1 
\end{bmatrix}$$

Como podemos observar, la diagonal de dicha representación matricial corresponde a la métrica de Minkowsky, así podemos escribir la relación de anticonmutación como,

$$ \gamma^u \gamma^v + \gamma^v \gamma^u = 2\mu^{uv} I_{4x4} \rightarrow \mu^{uv} = diag(1,-1,-1,-1) $$

Por lo que queda verificada que la anterior relación cumple con el álgebra de Clifford.


> # **8.1. MÍNIMOS CUADRADOS**

**$1)\verb| (Python)|$** Se tienen tres líneas en $\mathbb{R}^2$:

$$2x - y = 2$$
$$x + 2y = 1$$
$$x + y = 4$$

$(a)$ Con el método de mínimos cuadrados encuentre el punto común a las tres líneas. Grafique las tres líneas y el punto solución. ¿Qué interpretación puede dar?

$(b)$ Realice una búsqueda iterativa entre $-5 \leq x \leq 5$ y $-5 \leq y \leq 5$ con un paso de $h = 0.01$ para encontrar la menor distancia del problema. Grafique la distancia y compare con el resultado obtenido en los mínimos cuadrados.

- **$6)\verb| (Python)|$** En el caso de ajustes, es posible definir funciones de costo que midan la distancia entre los puntos muestrales y el modelo de ajuste. En el caso de mínimos cuadrados la función es $\mathfrak{X}^2$. Para $n$ puntos y un modelo lineal la función de costo es:

$$\mathfrak{X}^2(a_{0}, a_{1}) = \sum_{i = 1}^{n} (y_{i} - (a_{0} + a_{1}x_{i}))^2$$

Si hablamos en términos Bayesianos, $\omega = \{a_{0}, a_{1} \}$ define el conjunto de modelos lineales que pueden explicar $n$ puntos muestrales. Al minimizar $\mathfrak{X}^2(a_{0}, a_{1})$ muestre (analíticamente) que los parámetros están dados por:

$$a_{0} = \bar{y} - a_{1}\bar{x}$$
$$a_{1} = \frac{\sum xy - \dfrac{\sum x \sum y}{n}}{\sum x^2 - \dfrac{(\sum x)^2}{n}}$$

donde $\bar{x}$ y $\bar{y}$ son los valores medios de puntos y sus imágenes. Para $n$ puntos y un modelo cuadrático la función de costo es:

$$\mathfrak{X}^2(a_{0}, a_{1}, a_{2}) = \sum_{i = 1}^{n} (y_{i} - (a_{0} + a_{1}x_{i} + a_{2}x_{i}^2))^2$$

Minimize $\mathfrak{X}^2(a_{0}, a_{1}, a_{2})$ para encontrar el siguiente sistema de ecuaciones. *¿Nota alguna regularidad?*

$$\sum_{i = 1}^{n} \left[a_{0} + a_{1}x_{i} + a_{2}x_{i}^{2}  = y_{i} \right]$$
$$\sum_{i = 1}^{n} \left[a_{0}x_{i} + a_{1}x_{i}^{2} + a_{2}x_{i}^{3}  = x_{i}y_{i} \right]$$
$$\sum_{i = 1}^{n} \left[a_{0}x_{i}^{2} + a_{1}x_{i}^{3} + a_{2}x_{i}^{4}  = x_{i}^{2}y_{i} \right]$$

**Opcionalmente:** Encuentre los parámetros usando estas expresiones para los problemas $2)$ y $3)$.

**$7)\verb| Machine Learning: Logistic Regresion.|$** Descargue los datos de: https://raw.githubusercontent.com/asegura4488/Database/main/MetodosComputacionalesReforma/Sigmoid.csv

$(a)$ Defina el modelo de ajuste como:

$$M(x;\vec{\theta}) = \frac{\theta_{0}}{\theta_{1} + e^{-\theta_{2}x}}$$

donde el $\vec{\theta}$ es el vector de parámetros del ajuste.

$(b)$ Defina la métrica (función de costo) a minimizar como:

$$\mathfrak{X}^2(\vec{\theta}) = \sum_{i = 1}^{N} \left( \frac{y_{i} - M(x_{i}, \vec{\theta})}{\sigma_{i}} \right)^2$$

donde $\sigma_{i} = 1 \forall i$, es decir, no se consideran los errores de $y_{i}$.

$(c)$ Muestre que las derivadas parciales de la métrica están dadas por:

$$\frac{\partial\mathfrak{X}^2(\vec{\theta})}{\partial\theta_{i}} = -2 \cdot \sum_{i = 1}^{N}(y_{i} - M(x_{i}, \vec{\theta})) \cdot \frac{\partial M(x_{i}, \vec{\theta})}{\partial{\theta_{i}}}$$

$(d)$ Muestre que vectorialmente, el descenso del gradiente queda definido por:

$$\vec{\theta}_{j + 1} = \vec{\theta}_{j} - \gamma \cdot \left( -2 \cdot \sum_{i = 1}^{N}(y_{i} - M(x_{i}, \vec{\theta}_{j})) \cdot \nabla_{\theta} M(x_{i}, \vec{\theta}_{j}) \right)$$

donde el gradiente es respecto a los parámetros:

$$\nabla_{\theta} M(x_{i}, \vec{\theta}_{j}) = \left[ \frac{\partial M(x_{i}, \vec{\theta})}{\partial\theta_{0}}, \frac{\partial M(x_{i}, \vec{\theta})}{\partial\theta_{1}},\frac{\partial M(x_{i}, \vec{\theta})}{\partial\theta_{2}} \right]$$

$(e)$ Use una taza de aprendizaje $\gamma = 1 \times 10^{-3}$ o $\gamma = 5 \times 10^{-4}$, $\vec{\theta}_{0} = [1, 1, 1]$, un error de parada $\epsilon = 0.01$ y un máximo de iteraciones de $1 \times 10^{4}$.

$(f)$ Grafique los datos y the best fit model con sus parámetros.